import type { Word } from '@/types';

export const MAX_LEVEL = 5;

export const vocabulary: Word[] = [
  // Level 1
  {
    id: '1',
    text: 'Abate',
    definition: 'To become less intense or widespread.',
    level: 1,
    exampleSentence: 'The storm suddenly abated.',
    synonyms: ['subside', 'lessen', 'diminish', 'decline'],
    antonyms: ['intensify', 'increase', 'amplify'],
    roots: ['Old French "abattre" - to beat down', 'Latin "ad" - to + "battere" - to beat'],
  },
  {
    id: '2',
    text: 'Benevolent',
    definition: 'Well meaning and kindly.',
    level: 1,
    exampleSentence: 'A benevolent smile.',
    synonyms: ['kind', 'good-hearted', 'charitable', 'generous'],
    antonyms: ['malevolent', 'unkind', 'spiteful', 'miserly'],
    roots: ['Latin "bene" - well', 'Latin "volens" - wishing'],
    confusedWith: ['Beneficent (actively doing good, while benevolent is wishing good)'],
  },
  {
    id: '3',
    text: 'Candid',
    definition: 'Truthful and straightforward; frank.',
    level: 1,
    exampleSentence: 'His responses were remarkably candid.',
    synonyms: ['frank', 'outspoken', 'honest'],
    antonyms: ['guarded', 'secretive', 'evasive'],
  },
  {
    id: '4',
    text: 'Diligent',
    definition: 'Having or showing care and conscientiousness in one\'s work or duties.',
    level: 1,
    exampleSentence: 'Many caves are located only after a diligent search.',
    synonyms: ['hard-working', 'assiduous', 'conscientious'],
    antonyms: ['lazy', 'careless', 'negligent'],
  },
  {
    id: '5',
    text: 'Ephemeral',
    definition: 'Lasting for a very short time.',
    level: 1,
    exampleSentence: 'Fashions are ephemeral.',
    synonyms: ['transitory', 'fleeting', 'short-lived'],
    antonyms: ['permanent', 'lasting', 'eternal'],
    roots: ['Greek "ephemeros" - lasting a day'],
  },

  // Level 2
  {
    id: '6',
    text: 'Deleterious',
    definition: 'Causing harm or damage.',
    level: 2,
    exampleSentence: 'Divorce is assumed to have deleterious effects on children.',
    synonyms: ['harmful', 'damaging', 'detrimental'],
    antonyms: ['beneficial', 'harmless', 'helpful'],
  },
  {
    id: '7',
    text: 'Exacerbate',
    definition: 'Make (a problem, bad situation, or negative feeling) worse.',
    level: 2,
    exampleSentence: 'The forest fire was exacerbated by the strong winds.',
    synonyms: ['aggravate', 'worsen', 'intensify', 'compound'],
    antonyms: ['alleviate', 'improve', 'mitigate', 'reduce'],
    roots: ['Latin "ex-" - out, thoroughly', 'Latin "acerbus" - harsh, bitter'],
  },
  {
    id: '8',
    text: 'Fortuitous',
    definition: 'Happening by accident or chance rather than design.',
    level: 2,
    exampleSentence: 'From a cash standpoint, the company\'s timing is fortuitous.',
    synonyms: ['accidental', 'unexpected', 'unplanned', 'chance'],
    antonyms: ['planned', 'deliberate', 'intentional'],
    confusedWith: ['Fortunate (lucky, auspicious - while fortuitous means by chance, which may or may not be lucky)'],
  },
  {
    id: '9',
    text: 'Gregarious',
    definition: '(Of a person) fond of company; sociable.',
    level: 2,
    exampleSentence: 'He was a popular and gregarious man.',
    synonyms: ['sociable', 'convivial', 'outgoing'],
    antonyms: ['unsociable', 'reclusive', 'introverted'],
    roots: ['Latin "grex" (greg-) - flock, herd'],
  },
  {
    id: '10',
    text: 'Idiosyncratic',
    definition: 'Relating to idiosyncrasy; peculiar or individual.',
    level: 2,
    exampleSentence: 'She emerged as one of the great, idiosyncratic talents of the Nineties.',
    synonyms: ['peculiar', 'distinctive', 'eccentric'],
    antonyms: ['common', 'ordinary', 'conventional'],
  },

  // Level 3
  {
    id: '11',
    text: 'Juxtaposition',
    definition: 'The fact of two things being seen or placed close together with contrasting effect.',
    level: 3,
    exampleSentence: 'The juxtaposition of these two images.',
    synonyms: ['comparison', 'contrast', 'proximity', 'collocation'],
    roots: ['Latin "iuxta" - beside, near', 'French "position" - position'],
  },
  {
    id: '12',
    text: 'Mellifluous',
    definition: '(Of a voice or words) sweet or musical; pleasant to hear.',
    level: 3,
    exampleSentence: 'The voice was mellifluous and smooth.',
    synonyms: ['sweet-sounding', 'euphonious', 'dulcet', 'harmonious'],
    antonyms: ['cacophonous', 'harsh', 'grating'],
    roots: ['Latin "mel" - honey', 'Latin "fluere" - to flow'],
  },
  {
    id: '13',
    text: 'Nefarious',
    definition: '(Typically of an action or activity) wicked or criminal.',
    level: 3,
    exampleSentence: 'The nefarious activities of the organized-crime syndicates.',
    synonyms: ['wicked', 'evil', 'sinful', 'iniquitous', 'villainous'],
    antonyms: ['virtuous', 'good', 'righteous', 'honorable'],
    roots: ['Latin "nefas" - wrong, crime (from "ne-" - not + "fas" - divine law)'],
  },
  {
    id: '14',
    text: 'Obfuscate',
    definition: 'Render obscure, unclear, or unintelligible.',
    level: 3,
    exampleSentence: 'The spelling changes will deform some familiar words and obfuscate their etymological origins.',
    synonyms: ['confuse', 'obscure', 'cloud', 'muddy'],
    antonyms: ['clarify', 'elucidate', 'explain'],
    roots: ['Latin "obfuscare" - to darken (from "ob-" - over + "fuscus" - dark)'],
  },
  {
    id: '15',
    text: 'Pernicious',
    definition: 'Having a harmful effect, especially in a gradual or subtle way.',
    level: 3,
    exampleSentence: 'The pernicious influences of the mass media.',
    synonyms: ['harmful', 'destructive', 'damaging', 'deleterious', 'malignant'],
    antonyms: ['beneficial', 'harmless', 'benign'],
    roots: ['Latin "pernicies" - destruction, ruin (from "per-" - through + "nex" (nec-) - death)'],
  },

  // Level 4
  {
    id: '16',
    text: 'Ubiquitous',
    definition: 'Present, appearing, or found everywhere.',
    level: 4,
    exampleSentence: 'Sugar is ubiquitous in the modern diet.',
    synonyms: ['omnipresent', 'pervasive', 'widespread'],
    antonyms: ['rare', 'scarce', 'limited'],
    roots: ['Latin "ubique" - everywhere'],
  },
  {
    id: '17',
    text: 'Transient',
    definition: 'Lasting only for a short time; impermanent.',
    level: 4,
    exampleSentence: 'A transient cold spell.',
    synonyms: ['temporary', 'ephemeral', 'fleeting', 'short-lived'],
    antonyms: ['permanent', 'lasting', 'eternal', 'stable'],
    roots: ['Latin "transire" - to go across (from "trans-" - across + "ire" - to go)'],
  },
  {
    id: '18',
    text: 'Sagacious',
    definition: 'Having or showing keen mental discernment and good judgment; shrewd.',
    level: 4,
    exampleSentence: 'A sagacious advisor.',
    synonyms: ['wise', 'shrewd', 'astute', 'discerning'],
    antonyms: ['foolish', 'ignorant', 'naive'],
    roots: ['Latin "sagax" - of quick perception'],
  },
  {
    id: '19',
    text: 'Resilience',
    definition: 'The capacity to recover quickly from difficulties; toughness.',
    level: 4,
    exampleSentence: 'The resilience of the community after the earthquake.',
    synonyms: ['flexibility', 'elasticity', 'adaptability', 'toughness'],
    antonyms: ['fragility', 'vulnerability', 'weakness'],
    roots: ['Latin "resilire" - to leap back (from "re-" - back + "salire" - to leap)'],
  },
  {
    id: '20',
    text: 'Ambiguous',
    definition: 'Open to more than one interpretation; not having one obvious meaning.',
    level: 4,
    exampleSentence: 'The ending of the film is ambiguous.',
    synonyms: ['equivocal', 'unclear', 'vague', 'uncertain'],
    antonyms: ['clear', 'explicit', 'unambiguous', 'definite'],
    roots: ['Latin "ambiguus" - wavering (from "ambi-" - both + "agere" - to drive)'],
  },
  {
    id: '21',
    text: 'Capricious',
    definition: 'Given to sudden and unaccountable changes of mood or behavior.',
    level: 4,
    exampleSentence: 'A capricious and unpredictable woman.',
    synonyms: ['fickle', 'inconstant', 'changeable', 'unpredictable'],
    antonyms: ['consistent', 'stable', 'steadfast'],
    roots: ['Italian "capriccio" - sudden start, whim'],
  },
  {
    id: '22',
    text: 'Debilitate',
    definition: 'Make (someone) weak and infirm.',
    level: 4,
    exampleSentence: 'A debilitating illness.',
    synonyms: ['weaken', 'enfeeble', 'exhaust', 'incapacitate'],
    antonyms: ['strengthen', 'invigorate', 'energize'],
    roots: ['Latin "debilis" - weak'],
  },
  {
    id: '23',
    text: 'Egregious',
    definition: 'Outstandingly bad; shocking.',
    level: 4,
    exampleSentence: 'Egregious abuses of copyright.',
    synonyms: ['flagrant', 'atrocious', 'appalling', 'terrible'],
    antonyms: ['mild', 'minor', 'subtle'],
    roots: ['Latin "ex grege" - out of the flock'],
  },
  {
    id: '24',
    text: 'Fallacious',
    definition: 'Based on a mistaken belief.',
    level: 4,
    exampleSentence: 'Fallacious arguments.',
    synonyms: ['erroneous', 'false', 'incorrect', 'misleading'],
    antonyms: ['correct', 'true', 'accurate', 'valid'],
    roots: ['Latin "fallax" - deceitful'],
  },
  {
    id: '25',
    text: 'Garish',
    definition: 'Crudely bright or showy; tastelessly colorful.',
    level: 4,
    exampleSentence: 'Garish decorations.',
    synonyms: ['gaudy', 'loud', 'flashy', 'vulgar'],
    antonyms: ['somber', 'subdued', 'tasteful'],
    roots: ['Unknown origin'],
  },
  {
    id: '26',
    text: 'Haughty',
    definition: 'Arrogantly superior and disdainful.',
    level: 4,
    exampleSentence: 'A haughty waiter.',
    synonyms: ['arrogant', 'proud', 'vain', 'supercilious'],
    antonyms: ['humble', 'modest', 'meek'],
    roots: ['Old French "haut" - high'],
  },
  {
redefinition: 'Impossible to understand or interpret.',
    level: 4,
    exampleSentence: 'An inscrutable smile.',
    synonyms: ['enigmatic', 'mysterious', 'unreadable', 'impenetrable'],
    antonyms: ['understandable', 'clear', 'transparent'],
    roots: ['Latin "in-" - not + "scrutari" - to search into'],
  },
  {
    id: '28',
    text: 'Malinger',
    definition: 'Exaggerate or feign illness in order to escape duty or work.',
    level: 4,
    exampleSentence: 'He was malingering to avoid the army.',
    synonyms: ['shirk', 'dodge', 'loaf'],
    antonyms: ['work', 'toil'],
    roots: ['French "malingre" - ailing, sickly'],
  },
  {
    id: '29',
    text: 'Nostalgia',
    definition: 'A sentimental longing or wistful affection for the past, typically for a period or place with happy personal associations.',
    level: 4,
    exampleSentence: 'A wave of nostalgia swept over me.',
    synonyms: ['longing', 'wistfulness', 'sentimentality'],
    antonyms: ['forgetfulness'],
    roots: ['Greek "nostos" - return home', 'Greek "algos" - pain'],
  },
  {
    id: '30',
    text: 'Opaque',
    definition: 'Not able to be seen through; not transparent.',
    level: 4,
    exampleSentence: 'Opaque windows.',
    synonyms: ['cloudy', 'muddy', 'impenetrable', 'nontransparent'],
    antonyms: ['transparent', 'clear', 'translucent'],
    roots: ['Latin "opacus" - darkened'],
  },
  {
    id: '31',
    text: 'Plaudit',
    definition: 'An expression of praise or approval.',
    level: 4,
    exampleSentence: 'The committee gave her a well-deserved plaudit.',
    synonyms: ['praise', 'acclaim', 'applause', 'commendation'],
    antonyms: ['criticism', 'condemnation', 'boo'],
    roots: ['Latin "plaudere" - to applaud'],
  },
  {
    id: '32',
    text: 'Quell',
    definition: 'Put an end to (a rebellion or other disorder), typically by the use of force.',
    level: 4,
    exampleSentence: 'Additional forces were sent to quell the riot.',
    synonyms: ['suppress', 'put down', 'subdue', 'crush'],
    antonyms: ['incite', 'foment', 'stir up'],
    roots: ['Old English "cwellan" - to kill'],
  },
  {
    id: '33',
    text: 'Recalcitrant',
    definition: 'Having an obstinately uncooperative attitude toward authority or discipline.',
    level: 4,
    exampleSentence: 'A recalcitrant child.',
    synonyms: ['unruly', 'disobedient', 'refractory', 'willful'],
    antonyms: ['compliant', 'obedient', 'amenable'],
    roots: ['Latin "recalcitrare" - to kick back (from "re-" - back + "calx" - heel)'],
  },
  {
    id: '34',
    text: 'Soporific',
    definition: 'Tending to induce drowsiness or sleep.',
    level: 4,
    exampleSentence: 'The soporific effect of the heat.',
    synonyms: ['sleep-inducing', 'calming', 'tranquilizing'],
    antonyms: ['invigorating', 'stimulating', 'energizing'],
    roots: ['Latin "sopor" - deep sleep', 'Latin "facere" - to make'],
  },
  {
    id: '35',
    text: 'Tenuous',
    definition: 'Very weak or slight.',
    level: 4,
    exampleSentence: 'A tenuous connection.',
    synonyms: ['flimsy', 'fragile', 'shaky', 'weak'],
    antonyms: ['strong', 'firm', 'substantial'],
    roots: ['Latin "tenuis" - thin'],
  },
  {
    id: '36',
    text: 'Vacillate',
    definition: 'Alternate or waver between different opinions or actions; be indecisive.',
    level: 4,
    exampleSentence: 'I vacillated between the two options.',
    synonyms: ['waver', 'hesitate', 'fluctuate', 'sway'],
    antonyms: ['decide', 'resolve', 'stay'],
    roots: ['Latin "vacillare" - to sway'],
  },
  {
    id: '37',
    text: 'Wily',
    definition: 'Skilled at gaining an advantage, especially deceitfully.',
    level: 4,
    exampleSentence: 'A wily old politician.',
    synonyms: ['cunning', 'crafty', 'shrewd', 'sly'],
    antonyms: ['naive', 'gullible', 'straightforward'],
    roots: ['Old English "wigle" - sorcery'],
  },
  {
    id: '38',
    text: 'Zealous',
    definition: 'Having or showing great energy or enthusiasm in pursuit of a cause or objective.',
    level: 4,
exampleSentence: 'A zealous advocate for human rights.',
    synonyms: ['ardent', 'fervent', 'passionate', 'enthusiastic'],
    antonyms: ['apathetic', 'indifferent', 'lukewarm'],
    roots: ['Greek "zelos" - ardor, zeal'],
  },
  {
    id: '39',
    text: 'Abnegate',
    definition: 'Renounce or reject (something desired or valuable).',
    level: 4,
    exampleSentence: 'He attempts to abnegate personal responsibility.',
    synonyms: ['renounce', 'give up', 'reject', 'forsake'],
    antonyms: ['accept', 'embrace'],
    roots: ['Latin "ab-" - away + "negare" - to deny'],
  },
  {
    id: '40',
    text: 'Bilious',
    definition: 'Affected by or associated with nausea or vomiting; feeling or looking unpleasant.',
    level: 4,
    exampleSentence: 'A bilious shade of green.',
    synonyms: ['nauseous', 'unpleasant', 'sickly', 'peevish'],
    antonyms: ['pleasant', 'agreeable'],
    roots: ['Latin "bilis" - bile'],
  },




];

export const getWordsByLevel = (level: number): Word[] => {
  return vocabulary.filter(word => word.level === level);
}

export const getWordById = (id: string): Word | undefined => {
  return vocabulary.find(word => word.id === id);
}
